/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const supabaseurl = "sqdunrzdzgvlsjwahiem"
export const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZHVucnpkemd2bHNqd2FoaWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDQyMjcsImV4cCI6MjA3MjgyMDIyN30.Q35mlHbihuBYckIM45A0EY-OishLdEuAbPZSBmBQ6-E"